# Generated by Django 3.2.7 on 2021-09-24 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_testtttt',
            new_name='Post',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='insta_post__caption_73ecf4_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['caption'], name='insta_post_caption_f0d5c0_idx'),
        ),
    ]
