# Generated by Django 3.2.7 on 2021-09-26 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0003_auto_20210924_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='target_post',
            new_name='commnet_post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fg',
            field=models.ManyToManyField(blank=True, default=None, related_name='fg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fw',
            field=models.ManyToManyField(blank=True, default=None, related_name='fw', to=settings.AUTH_USER_MODEL),
        ),
    ]
